{{- if and (eq .Values.monitoring.agent "prometheus.io/operator") .Values.monitoring.operator }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capi-ops-manager.fullname" . }}-metrics-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-ops-manager.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "capi-ops-manager.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}