{{ template "azure-credential-manager.prepare-certs" $ }}

{{- if .Values.apiserver.enableMutatingWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "azure-credential-manager.fullname" . }}
  labels:
    {{- include "azure-credential-manager.labels" . | nindent 4 }}
webhooks:
  - name: vjob-v1.kb.io
    admissionReviewVersions:
      - v1
    failurePolicy: Fail
    sideEffects: None
    rules:
      - operations:
          - CREATE
          - UPDATE
          - DELETE
        apiGroups:
          - batch
        apiVersions:
          - v1
        resources:
          - jobs
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: {{ include "azure-credential-manager.webhookServiceName" . }}
        path: /mutate-batch-v1-job
      caBundle: {{ $._caCrt }}
{{- end }}
