{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-credential-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-credential-manager.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.azure.managedIdentityName }}
    klusters.dev/azure-mi-name: "{{ .Values.azure.managedIdentityName }}"
    {{- end }}
    {{- if .Values.azure.resourceGroupName }}
    klusters.dev/azure-rg-name: "{{ .Values.azure.resourceGroupName }}"
    {{- end }}
    {{- if .Values.azure.subscriptionId }}
    klusters.dev/azure-subscription-id: "{{ .Values.azure.subscriptionId }}"
    {{- end }}
automountServiceAccountToken: true
{{- end }}

