{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-credential-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "azure-credential-manager.labels" . | nindent 4 }}
  annotations:
    {{- if and (ne "" .Values.azure.tenantId)  (ne "" .Values.azure.clientId) }}
    "azure.workload.identity/tenant-id": "{{ .Values.azure.tenantId }}"
    "azure.workload.identity/client-id": "{{ .Values.azure.clientId }}"
    {{- end }}
automountServiceAccountToken: true
{{- end }}