apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aws-credential-manager.fullname" . }}:leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-credential-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aws-credential-manager.fullname" . }}:manager
  labels:
    {{- include "aws-credential-manager.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aws-credential-manager.fullname" . }}:leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-credential-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "aws-credential-manager.fullname" . }}:leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "aws-credential-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-credential-manager.fullname" . }}:manager
  labels:
    {{- include "aws-credential-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "aws-credential-manager.fullname" . }}:manager
subjects:
- kind: ServiceAccount
  name: {{ include "aws-credential-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-credential-manager.fullname" . }}:metrics-auth
  labels:
    {{- include "aws-credential-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "aws-credential-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
