{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "capa-vpc-peering-operator.fullname" . }}-metrics-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capa-vpc-peering-operator.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "capa-vpc-peering-operator.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
