{{- if eq .Values.monitoring.agent "prometheus.io/operator" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcp-credential-manager.fullname" . }}-metrics-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gcp-credential-manager.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "gcp-credential-manager.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}